name: Build
on: 
  push:
    branches:
      - '*'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build api image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: shopping-basket-api:latest
          context: "{{defaultContext}}:src"
      